const carBrands: readonly string[] = [
    'Audi',
    'BMW',
    'Ford',
    'Geely',
    'Haval',
    'Honda',
    'Hyundai',
    'Kia',
    'Lada',
    '(ВАЗ)',
    'Mazda',
    'Mercedes-Benz',
    'Mitsubishi',
    'Nissan',
    'Renault',
    'Skoda',
    'Toyota',
    'Volkswagen',
    'Acura',
    'Daihatsu',
    'Datsun',
    'Honda',
    'Infiniti',
    'Isuzu',
    'Lexus',
    'Mazda',
    'Mitsubishi',
    'Nissan',
    'Scion',
    'Subaru',
    'Suzuki',
    'Toyota',
];

export default carBrands;
